# Python libraries for scientific computing and data analysis
---

These Python libraries contain many important functions that are 
useful in data analysis.

* `numpy` - Contains functions to operate on vectors, matrices and higher-dimensional collections of numbers succinctly.

* `scipy` - Contains functions for scientific programming:
    * `scipy.stats` - Statistics
    * `scipy.optimize` - Optimization
    

* `matplotlib` - A plotting library. 

In this notebook, we'll briefly explore the first of these libraries, `numpy`. `numpy` (pronounced like "numb pie") provides data structures and functions to work with multi-dimensional arrays, vectors and matricies. This is not meant to provide an exhaustive exploration of all the features and functionality built into `numpy`. Instead, we will provide a cursory overview of many basic core idea in `numpy`, and delve deeper into details when needed throughout the semester.

## Vectors (1D arrays) in `numpy`
---

As motivation, consider the following example:

#### Example
Recall that for a vector

$$ \mathbf v = (v_1, v_2, ..., v_n) $$

it's length (or *Euclidean norm*) is given by

$$ \| \mathbf v \| = \sqrt{\sum_{i=1}^n v_i^2}, $$

It's entirely possible to define a vector and a function to compute that vector's length using ordinary Python lists without an external library such as `numpy`.

In [1]:
# We'll first define a vector just as a Python list of numbers
v_list = [3, -1, 0, 5, 2, 3]

# Calculate norm using a for-loop.
squared_sum = 0
for v in v_list:
    squared_sum = squared_sum + v**2

# Take square root to get the length
norm = squared_sum**0.5

# Print the result
print(norm)

6.928203230275509


We can alternatively use some `numpy` functions to do a lot of this for us. The first thing we'll do is to convert this list into a **`numpy` array**, sometimes called an `ndarray`:

In [2]:
# import the numpy library and give it a short alias
# you only have to do this once.
import numpy as np

# Turn v_list into a numpy array
v_arr = np.array(v_list)

Above, we imported the numpy library into our code, and we also gave in an alias using `as np`. This way, we can refer to any `numpy` function using `np` rather than `numpy`, which shortens the code a little bit. We then used the `numpy` function `np.array` to convert the Python list into a `numpy` array.

In many respects, `numpy` arrays look and behave like Python lists. Printing both the list and array out we get the same thing:

In [3]:
print(v_arr)
print(v_list)

[ 3 -1  0  5  2  3]
[3, -1, 0, 5, 2, 3]


The `len` function still works, as does indexing and slicing into a numpy array:

In [4]:
print(len(v_arr))

6


In [5]:
print(v_arr[2])

0


In [6]:
print(v_arr[:4])
print(v_arr[-3:-1])

[ 3 -1  0  5]
[5 2]


They are different types, however:

In [7]:
print(type(v_arr))
print(type(v_list))

<class 'numpy.ndarray'>
<class 'list'>


The `numpy` array type lets us do more things to `v_arr` than what we could do with a plain list like `v_list`. One thing we can do is apply the same operation to every element in the array without having to write a `for`-loop or a list comprehension.

In [8]:
squared_values = v_arr**2
print(squared_values)

[ 9  1  0 25  4  9]


You can't do that with a normal Python list:

In [9]:
# You can't "square" a normal Python list.
v_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

To do the same, you'd have to use a `for`-loop or a list comprehension:

In [10]:
squared_list_values = [v**2 for v in v_list]
print(squared_list_values)

[9, 1, 0, 25, 4, 9]


However, the numpy version is faster. To appreciably see this in time-scales we as humans are used to, we'll repeat the same squaring operation one million times on a list with 1000 uniform-random sampled entries. We'll use the `timeit` library to measure the time it takes to do this.

In [11]:
import timeit
import random

v_list = [random.random() for _ in range(1000)]
v_arr = np.array(v_list)

tic = timeit.default_timer()

for _ in range(1000000):
    squared_values = v_arr**2
    
toc = timeit.default_timer()

print("Elapsed time = %5.2f seconds" % (toc - tic))

Elapsed time =  1.34 seconds


Repeating the same timing but with the vanilla Python list:

In [12]:
tic = timeit.default_timer()

for _ in range(1000000):
    squared_list_values = [v**2 for v in v_list]
    
toc = timeit.default_timer()
print("Elapsed time = %5.2f seconds" % (toc - tic))


Elapsed time = 82.77 seconds


We see that in this case, the `numpy` version is around 64 times as fast as the normal Python version. This is typical of this and other  **vectorized** operations in `numpy` -- they are orders-of-magnitude faster than what you could code up in Python. Therefore, one important rule-of-thumb is **to use `numpy` functions as much as you can.** Consult the `numpy` documentation for details of what operations you can perform on `numpy` arrays. There are a lot of `numpy` functions on `numpy` arrays, and we'll go over some basic operations here and throughout the class.

(For those interested, one reason vectorized `numpy` is faster is because `numpy` doesn't actually perform the looping and many operations using Python. Instead, it does these operations in compiled C code, which is much faster than interpreted Python code.)


For example, we can do some vector arithmetic as well:

In [13]:
v = np.array([1, 2, 3, 4, 5, 10])
print("        v = " + str(v))

# Scalar multiplication
w = 3*v
print("  w = 3*v = " + str(w))

# Add and substract
z = w - v
print("z = w - v = " + str(z))

        v = [ 1  2  3  4  5 10]
  w = 3*v = [ 3  6  9 12 15 30]
z = w - v = [ 2  4  6  8 10 20]


Note in particular that unlike Python lists, `3*v` does not repeat `v` 3 times, but multiplies each element of `v` by 3.

You can even add a constant vector to another vector without having to explicitly build that vector. For example, to substract 42 from every element of `v`, you could calculate:

In [14]:
y = v - 42
print(y)

[-41 -40 -39 -38 -37 -32]


Therefore, even though `v` is a vector, and 42 is a number, `numpy` knows you mean substracting 42 from every element. What happens behinds the scenes is that the number 42 becomes *broadcasted* into a vector of appropriate length in order for the substraction to make sense. [Numpy broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) is a rich and deep subject that we'll touch on occassionally throughout the course.

We also have access to many `numpy` functions, such as `numpy.sum`, which sums all elements in an array:

In [15]:
v_sum = np.sum(v)
print(v_sum)

25


This, together with the squaring operator and the `numpy.sqrt` function gives us a way of quickly computing norms.

In [16]:
# Calculate norm with squaring and summation
norm_squared = np.sum(v**2)
norm = np.sqrt(norm_squared)
print(norm)

12.449899597988733


In spirit, the code above does the same thing as the for-loop at the beginning of the notes: 
1. It squares every element of `v`,
2. It sums these squared elements of `v`,
3. It calculates the square of this sum-of-squares to get the norm.

However, this code is only 3 lines and runs much faster than the native Python code.

Of course, there's a shorter way to do this, because `numpy` has some built-in Linear algebra functions, most of which are contained in the submodule `numpy.linalg`. In particular, you can calculate the norm of a vector using `np.linalg.norm`.

In [17]:
norm = np.linalg.norm(v)
print(norm)

12.449899597988733


#### Exercise
---

Recall that the Euclidean distance between two vectors $\mathbf v$ and $\mathbf w$ is the norm of their difference

$$ D(\mathbf v, \mathbf w) = \| v - w \| $$

Given two python lists `v_list` and `w_list`, use `numpy` to calculate the distance between them.

How long does it take to run this function 1M times, each time on randomized inputs. You can sample random inputs using the code

```
v_list = [random.random() for _ in range(1000)]
w_list = [random.random() for _ in range(1000)]
```

---


In [18]:
def distance(v_list, w_list):
    # Function code goes here

SyntaxError: unexpected EOF while parsing (<ipython-input-18-26b394fb47ff>, line 2)

## Matrices (2D arrays) in `numpy`
---

Matrices in `numpy` are 2D arrays, which are wrappers around basic python list-of-lists

In [19]:
A_list_of_lists = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

# Turn python list of lists to a numpy 2D array
A = np.array(A_list_of_lists)
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Like (1D) vectors, `numpy` matrices are also consider ndarrays:

In [20]:
print(type(A))

<class 'numpy.ndarray'>


All `numpy` arrays have some `built-in` auxillary values that you can access by the `.` notation. For example, all arrays have a `.shape` that tells you the dimensions of the array.

In [21]:
print(A.shape)

(4, 3)


The result of `A.shape` is a `tuple`, object, which is kind of like a list with two entries. For example, you can access the individual dimensions

In [22]:
dims = A.shape

print("number of rows:")
print(dims[0])

print("number of columns:")
print(dims[1])

number of rows:
4
number of columns:
3


You can also access the transpose of a matrix using `.T`

In [23]:
print(A.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [24]:
print(A.T.shape)

(3, 4)


The `len` function applied to matrices will report how many rows the matrix has. It is therefore equivalent to `A.shape[0]`.

In [25]:
print(len(A))
print(A.shape[0])

4
4


Like vectors, we can perform matrix operations on `numpy` 2D arrays. These operations are performed element-wise:

In [26]:
print(A**2)

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]


In [27]:
print(A**2 - A)

[[  0   2   6]
 [ 12  20  30]
 [ 42  56  72]
 [ 90 110 132]]


In [28]:
print(0.1*A)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [1.  1.1 1.2]]


We can sum all of the elements in A, across all rows and across all columns using the `np.sum` command:

In [29]:
total_sum = np.sum(A)
print(total_sum)

78


While sometimes this is useful, more often we'll be interested in the sum of all rows or columns. To do this, we can use the special `axis` argument to `np.sum` and many other `numpy` functions. Specifying the `axis` argument will specify what dimension over which to perform the summation.

For example, if we use `np.sum(A, axis = 0)`, this is saying we wish to sum down columns -- effectively marginalizing over rows (the 0-th dimension of a matrix).

In [30]:
col_sums = np.sum(A, axis = 0)
print(col_sums)

[22 26 30]


Here the $i$-th entry of `col_sums` is the sum of all the entries of the $i$-th **column**.

In [31]:
print(col_sums.shape)

(3,)


In general, for `np.sum` and other similar `numpy` functions that aggregate data, specifying `axis = i` computes the aggregation over the `i`-th dimension, eliminating it from the result. Thus if your matrix is $m \times n$, then `np.sum(A, axis = 0)` will sum over and eliminate the 0-th dimension (rows), resulting in a vector of length $n$ -- one sum for every column -- while `np.sum(A, axis = 1)` will sum over and eliminate the 1-st dimension (columns, resulting in a vector of length $m$ -- one sum for every row.

### Matrix-vector operations

We can perform matrix vector multiplication

$ A \mathbf x = \mathbf b$

We can use the `@` symbol to do this:

In [32]:
# Define a vector x = (1, 2, 3)
x = np.array([1, 2, 3])

# Do the multiplication
b = A @ x

print("A = ")
print(A)

print("x = ")
print(x)

print("b = ")
print(b)

A = 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
x = 
[1 2 3]
b = 
[14 32 50 68]


Notice that unlike in Matlab, here we don't distinguish between row and column vectors, in this case, since `x` is a 1D array, `numpy` tries its best to interpret this correctly.

In [33]:
print(x.shape)
print(b.shape)

(3,)
(4,)


This flexibility is a bit annoying. For example, `numpy`'s flexibility and broadcasting rules means `numpy` will interpret what `A * x` is, and it is **NOT** matrix-vector multiplication:

In [34]:
print(A * x)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]
 [10 22 36]]


This and other "broadcasting magic" has lead to real-life bugs in the past. If you wish to be sure, when doing linear algebra, you could use 2D arrays to distinguish between row and column vectors. The easiest way to do this is with the special `np.newaxis` index, which adds a trivial dimension to any vector. For example, by doing the following, we turn convert `x` into `xx`, a column vector.

In [35]:
xx = x[:, np.newaxis]
print(xx.shape)

(3, 1)


That is, `xx` has 3 rows and 1 column. We can do the appropriate matrix multiplication to A, to get the result, which we save as `bb`.

In [36]:
bb = A@xx

print(bb)
print(bb.shape)

[[14]
 [32]
 [50]
 [68]]
(4, 1)


We see that it is properly a $4\times 1$ column vector, which is what you would expect when multiplying a $4 \times 3$ matrix with a $3 \times 1$ column vector. This also prevents the misinterpretation above:

In [37]:
print(A * xx)

ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

Here, due to the extra dimension, `numpy` cannot interpret how to "correctly" broadcast `xx`, so it fails.

This is not to say that you *should* do things like this, but instead to be absolutely careful about your operations. Always test and debug your code to make sure you are getting the outputs you are expecting, such as the shape of arrays, their dimenions, etc. It is also something to look out for if you are trying to find a bug in your code -- always check your shapes!

#### Excercise
---

The `np.linalg.lstsq(A, b)` function solves the linear equation 

$$ A \mathbf x = \mathbf b, $$

for the vector $\mathbf x$ to the best of its abilities (we'll talk about this more in class).

Solve the above system where

$$ A = \begin{pmatrix} 2 & 4 & 3 \\ 1 & 3 & -2 \\ -4 & 1 & 3 \end{pmatrix}, \quad \mathbf b = \begin{pmatrix} 16 \\ 8 \\ -8.5 \end{pmatrix}$$

For a proposed solution $\mathbf x$ to the above equation, the **residual** is the vector

$$ \mathbf r = A \mathbf x - \mathbf b,$$

If $\mathbf x$ perfectly solved the system, the residual would be $\mathbf 0$. Otherwise, its norm $\|\mathbf r\|$ can be used as a measure of error.

* Calculate the residual for the system above.

* Using the residual and some `numpy` operations and functions, calculate the **mean squared error**:

$$ \text{MSE} = \frac{1}{n} \sum_{i=1}^n ((A\mathbf x)_i - b_i)^2, $$

where $(A\mathbf x)_i$ is the $i$-th component of the vector that is the result of the multiplication $A\mathbf x$, and $b_i$ is the $i$-th component of the vector $\mathbf x$. Note that this is literally the mean (or average) of the squares of the error.


---


## Accessing array elements
---

Accessing elements and sub-arrays can be done by indexing rows and columns, indexing rows and columns separately . For example, to get the element at row 0 and column 2, you would use `A[0,2]`.

In [39]:
# Print the whole matrix for reference
print(A)

# Print the element at (0, 2)
print(A[0,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3


The standard rules apply here: you can use positive and negative integers, or slices, and all the indexing is zero-based. Apart from being zero-based, this is very similar to how things are done in Matlab. For example, to access the entire 3rd row, we use an index `3` in the first "slot" to get the 3rd row, and in the second slot, we specify a slice 0:3 to access the 0-th, 1st, and 2nd column (i.e. all the columns)

In [40]:
print(A[3,0:3])

[10 11 12]


Again, because the end-points of the slice are 0 and the length of the entire row, we don't really need to specify them, as they'll be filled in automatically.

In [41]:
print(A[3,0:])

[10 11 12]


In [42]:
print(A[3,:3])

[10 11 12]


In [43]:
print(A[3,:])

[10 11 12]


This last example is the preferred method for accessing an entire row of a matrix, because it's shorter.

Instead of accessing the entire row, you can specify what columns you wish to access, such as only the last two columns of the 3rd row.

In [44]:
print(A[3,1:])

[11 12]


Access everything in the row but the last column (i.e. the first two columns)

In [45]:
print(A[3,0:-1])

[10 11]


Of course, you can do the same with the rows as well, and even combine slicing rows and columns. For example, get the first two rows and columns:

In [46]:
print(A[:2, :2])

[[1 2]
 [4 5]]


This is a $2\times 2$ sub matrix of the matrix $A$.

### Indexing by list

We've seen examples of accessing elements from a numpy array using numbers and slices. Another way to access entries and sub-arrays is with lists (or list-like objects) of rows and columns.

First, we'll define a larger matrix to better illustrate our points below. The entries in the matrix `B` below indicate their row and column positions, with the element at position $(i, j)$ has $i$ in the 10s place and $j$ in the 1s place. 

In [47]:
B = np.array([[10*i + j for j in range(5)] for i in range(10)])
print(B)
print("B has shape = " + str(B.shape))

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]
 [60 61 62 63 64]
 [70 71 72 73 74]
 [80 81 82 83 84]
 [90 91 92 93 94]]
B has shape = (10, 5)


We can access the even rows by specifying a list of indices.

In [48]:
I = [0, 2, 3, 4, 8]

# Access only the rows indexed by elements of I (and all the columns)
print(B[I, :])

[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [80 81 82 83 84]]


We can actually use any list-like object. For example, we can use the `range` function, to specify the same indices.

In [49]:
I = range(0, 10, 2)
print(B[I, :])

[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [40 41 42 43 44]
 [60 61 62 63 64]
 [80 81 82 83 84]]


Of course, this applies to rows and columns the same way. To get the 3rd and 4th column:

In [50]:
J = [3, 4]

print(B[:, J])

[[ 3  4]
 [13 14]
 [23 24]
 [33 34]
 [43 44]
 [53 54]
 [63 64]
 [73 74]
 [83 84]
 [93 94]]


Some care has to be taken when trying to do this to both rows and columns. For example, if you wanted to access the the even rows and the 3rd and 4th column, you can't actually do the obvious:

In [51]:
# This will result in an error
print(B[I, J])

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (5,) (2,) 

The above error has something to do with the shape of the inputs and a `numpy` concept called broadcasting. We won't go over this here for now, but the solution is to change the shape of the input arrays, converting the index set from a "row vector" to a "column vector" by making it a list-of-lists, namely a list of 5 lists, each having one element each, instead of one list with 5 elements.

In [54]:
I = [[0], [2], [4], [6], [8]]
print(B[I, J])

[[ 3  4]
 [23 24]
 [43 44]
 [63 64]
 [83 84]]


You don't have to access the rows/columns in order. If you specify your indices out of order, the resulting sub-matrix will have the rows/columns in the order you specify.

In [55]:
I = [ 8, 4, 0]

print(B[I, :])

[[80 81 82 83 84]
 [40 41 42 43 44]
 [ 0  1  2  3  4]]


This can be used in conjunction with `np.argsort`, which returns a list of indices in sorted order, to sort a matrix according to a specific row.

For example consider a different matrix below (which we generate using another `numpy` function called `np.random.normal` -- which is not important enough to discuss right now).

In [56]:
C = np.random.normal(0, 1, [10, 5])
print(C)

[[-1.37990349  0.09113806 -0.20820994 -0.0562635  -0.88048408]
 [-0.45872436  0.66415358 -0.28837473  0.86557048 -0.25030236]
 [-0.77213894 -0.88294236  0.41637665 -2.4109548  -1.30969699]
 [ 0.60101044  0.03028043  0.37155057  1.09097454 -0.49472912]
 [ 1.01620945  1.22154101  1.52055633 -2.27601417 -0.76389648]
 [-0.86231131  0.08643817  0.45670279  0.98067731  0.38239698]
 [ 0.92891897 -0.18753757  0.13088854 -1.11092221 -0.55091423]
 [-0.13424451 -0.05244601  0.75520311 -0.57375356 -0.98560386]
 [ 0.94480325 -0.29183058  0.06929703  0.56794295 -0.03774539]
 [ 0.87771362  2.56594012 -0.98909164 -0.16883342  0.84235178]]


To sort by the 3rd column, we can use `np.argsort` on the 3 column:

In [57]:
I = np.argsort(C[:, 3])
print(I)

[2 4 6 7 9 0 8 1 5 3]


This says that, in the 3rd column, the 0-th entry is the smallest, followed by the 7th, etc. Therefore, we can use this to index into the `C` matrix to extract rows in this order:

In [58]:
print(C[I, :])

[[-0.77213894 -0.88294236  0.41637665 -2.4109548  -1.30969699]
 [ 1.01620945  1.22154101  1.52055633 -2.27601417 -0.76389648]
 [ 0.92891897 -0.18753757  0.13088854 -1.11092221 -0.55091423]
 [-0.13424451 -0.05244601  0.75520311 -0.57375356 -0.98560386]
 [ 0.87771362  2.56594012 -0.98909164 -0.16883342  0.84235178]
 [-1.37990349  0.09113806 -0.20820994 -0.0562635  -0.88048408]
 [ 0.94480325 -0.29183058  0.06929703  0.56794295 -0.03774539]
 [-0.45872436  0.66415358 -0.28837473  0.86557048 -0.25030236]
 [-0.86231131  0.08643817  0.45670279  0.98067731  0.38239698]
 [ 0.60101044  0.03028043  0.37155057  1.09097454 -0.49472912]]


Here we see the rows are permutted in increase order by the 3rd column.

#### Exercise
---

In the above exaple, `I` is a list. How would you use this fact, to change this example to only include the top 4 rows (with respect to the 3rd column) with one line of code?

---


### Boolean indexing

Another **very important** method of accessing `numpy` arrays is by Boolean indexing. With Boolean indexing, instead of explicitly listing the indices of columns or rows you wish to keep, you specify a list of `True` or `False` values to flag which rows you wish keep, with one entry for every column or row. 

For example, we'll specify a Boolean list (one that only has `True` or `False` values) of length 10 -- the same number of rows in `B`, and indicate which rows we wish to keep, and which we don't.

In [59]:
I = [True, True, False, False, False, False, True, False, True, False]
print(B[I, :])

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [60 61 62 63 64]
 [80 81 82 83 84]]


Because the list `I` above has a `True` in positions 0, 1, 6, and 8, we  access those rows to get the result above.

On its own, using such Boolean lists seem like more work than just individually specifying which rows you wish to keep. However, the power of Boolean indexing comes with the ability to quickly build such lists through vectorized  conditionals. For example, we can ask which rows have a 3rd column larger than 40, and extract only those rows:

In [60]:
I = B[:, 3] > 40
print(I)

[False False False False  True  True  True  True  True  True]


Here we see that we can quickly build up such boolean lists by checking conditions on the matrix rows or columns. From this, we can simply index the rows indicated in `I`:

In [61]:
print(B[I, :])

[[40 41 42 43 44]
 [50 51 52 53 54]
 [60 61 62 63 64]
 [70 71 72 73 74]
 [80 81 82 83 84]
 [90 91 92 93 94]]


This is incredibly useful for filtering data based on some conditions. The conditions can be fairly complex. 

For example, let's pretend that the matrix `C` above is a data set, in which every row is a data point, and the columns correspond to different dimensions of the data. Specifically, we'll pretend that this data was obtained by making 3 types of measurements at a material sample at different points $(x, y)$. Each row of `C` holds these 3 measurements at one point, which is also saved in `C`. We'll assume that the 0-th and 1-st column of `C` store these $(x, y)` coordinates (measured in nanometers, nms).

Suppose we suspect that there is something different going on at the core of the sample -- points within a radius of 0.8 nm form the origin. We would want to explore the data at such points and compare with the other data points to see if something different is actually happening and being captured in the measurements. 

To do this, we will condition on the distance of a data point from the origin, then extract only those inside a radius of 0.8. The distance is calculated as

In [62]:
r = np.linalg.norm(C[:, [0,1]], axis = 1)
print(r)

[1.38290989 0.80717285 1.17293893 0.60177275 1.5889758  0.86663277
 0.9476607  0.14412554 0.98884694 2.71190521]


**Study the above line carefully. Make sure you understand all the parts to it.** The end result is that `r` holds the distance from the origin for every point in the data set representedby `C`. It has 10 elements, because there are 10 rows in `C`. Now we form a condition to extract those rows whose corresponding distance is less than 0.8


In [63]:
I_core = r < 0.8
C_core = C[I_core, :]

print(C_core)

[[ 0.60101044  0.03028043  0.37155057  1.09097454 -0.49472912]
 [-0.13424451 -0.05244601  0.75520311 -0.57375356 -0.98560386]]


Here `C_core` reprents the subset of data corresponding to measurements made in the core region. This was done using the Boolean index list:

In [64]:
print(I_core)

[False False False  True False False False  True False False]


By flipping `True` and `False` values, we can get the complement of this data -- namely the data corresponding to measurements made outside of the core region. To do this, we can use the **bitwise not** operator `~`

In [65]:
I_edge = ~I_core
print(I_edge)

[ True  True  True False  True  True  True False  True  True]


Using this, we can extract the compliment of the core data

In [66]:
C_edge = C[I_edge, :]

Other bitwise logical operations can be used to combine conditionals including the bitwise AND operator: `&`, and the bitwise OR operator `|`.

**It is important to master and understand Boolean indexing**, because of its ability to quickly and succinctly filter data sets. Many students who do not end up spending a long amount of time writing and debugging difficult code to do this filtering, when one or two lines of Boolean indexing would have worked.

#### Exercise
---

The matrix called `data` below represents 100 measurements of the strength of a material grown at a particular temperature, pressure and growth time. The matrix has 100 rows (one for every measurement) and 4 columns, where the 0th, 1st, and 2nd column specify the grownth coditions, and the last (3rd) column specifies the measured strength of the materials.

You want to identify those cases with anomously high strength. Namely, you want to figure out which data points have a strength whose value is at least 3 orders of magnitude larger than the mean. Namely, such a data point would have a strength $s$ such that

$$s > \mu + 3 \sigma,$$

where $\mu$ is the mean of all the measured strengths and $\sigma$ is the standard deviation of the measured strengths. For any vector of numbers, `v`, you can calculate its mean and standard deviation using the `numpy` functions:

```
mu = np.mean(v)
sig = np.std(v)
```

How do you find extract the anomolous data points for further analysis?

In [67]:
# Artifical data
data = np.random.normal(0, 1, [100, 4])
print(data.shape)

#
#
# Your code goes here
#
#

(100, 4)


## Numpy array creation and initialization
---

There are many ways to create, initialize or load data into a numpy array. The first way is to take an existing list of numbers, or list-of-lists of numbers (or even more), and use the `np.array` function to convert it into an array.

Another way is to specify a vector, matrix or higher-dimensional array of all 1s, using the `np.ones` function.

In [68]:
# A vector with three 1s.
v = np.ones(3)
print(v)

[1. 1. 1.]


In [69]:
# A 5x4 matrix of 1s
A = np.ones([5,4])
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [70]:
# A higher dimensional array of all 1s
# It's like having three 4x5 matrices, all with all 1s.
Z = np.ones([3, 4, 5])
print(Z.shape)
print(Z)

(3, 4, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


If you want a different number other than 1, you can simply multiply the result by that number, or use the `numpy` function `np.fill`.

In [71]:
B = 3*np.ones([2,5])
print(B)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [72]:
B = np.full([2,5], 3)
print(B)

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [73]:
Z = 0*np.ones([3, 3])
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


A better way of getting a matrix of all zeros is to use the `np.zeros` function:

In [74]:
Z = np.zeros([3,3])
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


This is often done to **pre-allocate** the space in memory for the matrix `Z`, if you have some complex code to compute its elements.

### Concatenating arrays

You can **append** compatiably shaped arrays together. For example, suppose you have a data set that is represented by a $100x4$ matrix `data`, where each row is a data point (so that you have 100 data points). Suppose you get a new data point which is a vector of length 4.

In [75]:
data = np.random.normal(0, 1, [100, 4])
print(data.shape)

new_datapoint = np.random.normal(0, 1, [1,4])
print(new_datapoint.shape)

(100, 4)
(1, 4)


To use `numpy.append` to append the new datapoint to the existing data set, you must be careful.

In [76]:
new_data = np.append(new_datapoint, data)
print(new_data.shape)

(404,)


As we see above, the default behavior of `np.append` was to flatten everything into a single-dimensional vector. This is similar to the behavior of `np.sum` -- unless we specify an `axis`, `np.sum` and `np.append` will just kind of ignore how your data is organize, and treat everything as a flat array.

Thus, you must make sure you specify what axis we're adding to. Here, we have a new **row**, so we are adding to the row dimension (`axis = 0`):

In [77]:
new_data = np.append(new_datapoint, data, axis = 0)
print(new_data.shape)

(101, 4)


Note that the original `data` did not change, it still has 100 rows:

In [78]:
print(data.shape)

(100, 4)


Here it was important that `new_datapoint.shape` was a 1x4 2D array

In [79]:
print(new_datapoint.shape)

(1, 4)


For all the flexibility `numpy` tries to afford when it comes to shapes and broadcasting, this is one example where it is particuarly stubborn. In order to append one `numpy` array to another using:

```
np.append(A, B, axis = i)
```

then two conditions must be satisfied:

1. `A` and `B` must both have the same dimensions (as in, must both be 1D arrays, or 2D arrays, or 3D arrays, etc.) That is ``len(A.shape) == len(B.shape)``.

2. The shapes of `A` and `B` must agree for all dimensions other than dimension `i`. That is `A.shape[j] == B.shape[j]` whenever `j` is not equal to `i`.

In particular, if `new_datapoint` was just a 4-long 1D array, then the above code would fail.

In [80]:
new_datapoint = np.random.normal(0, 1, 4)
print(new_datapoint.shape)

(4,)


In [81]:
new_data = np.append(new_datapoint, data, axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

This tends to be a headache whenever you encounter this. To fix this, you can succintly add the required extra dimension using a special index `np.newaxis`, which actually adds a new dimension to your data

In [82]:
# Treats new_datapoint as a 4x1 column vector.
print(new_datapoint[:, np.newaxis].shape)

(4, 1)


In [83]:
# Treats new_datapoint as a 1x4 row vector.
print(new_datapoint[np.newaxis, :].shape)

(1, 4)


This latter case is what we need to append the new data as a new row to the data set.

In [84]:
new_datapoint = np.random.normal(0, 1, 4)
print(new_datapoint.shape)
new_data = np.append(new_datapoint[np.newaxis,:], data, axis = 0)
print(new_data.shape)

(4,)
(101, 4)


The `np.concatenate` function is like `append`, but works for several arrays at a time, and not just two. Similar conditions hold for the set of arrays passed to `np.concatenate` as they did for the pair of arrays passed to `np.append`, namely the constraints on dimension and shape. To use it, you must pass a sequence of arrays as the first argument to `np.concatenate`:

In [85]:
Z1 = np.random.normal(0, 1, [10, 4])
Z2 = np.random.normal(0, 1, [33, 4])
Z3 = np.random.normal(0, 1, [65, 4])

# Concatenate together. Notice the first argument
# is (Z1, Z2, Z3)
Z = np.concatenate( (Z1, Z2, Z3), axis = 0)
print(Z.shape)

(108, 4)


Of course, both `np.concatenate` and `np.append` work for columns and other dimensions as well by setting the `axis` argument appropriately.


### Preallocation vs. concatenation

While there is a time and place for concatenation/appending matrices together, try to use this sparingly, especially inside your main data-processing loop. The main reason is due to memory allocation -- concatenating existing matrices together requires requesting more memory from the operating system, and this is expensive.

If you know who many rows or columns a matrix you are computing will have, then it is better to preallocate using `np.zeros` than to continuously appending new entries as you go.

For example, consider the problem of calculating some summary statistics for rows of a data set. Below, we use `np.append` to continuously append the mean and standard deviation of every row of a data matrix.



In [86]:
all_stats = np.zeros([0, 2])
data = np.random.uniform(0, 1, [100000, 100])

tic = timeit.default_timer()

for i in range(len(data)):
    # Calculate the row's mean and standard deviation
    row_stats = np.array([np.mean(data[i,:]), np.std(data[i,:])])
    
    # Append to all_statistics
    all_stats = np.append(all_stats, row_stats[np.newaxis, :])
    
toc = timeit.default_timer()

print("Elapsed time = %5.2f seconds"%(toc - tic))


Elapsed time =  7.74 seconds


In [87]:
# pre-allocate the matrix
all_stats = np.zeros([len(data), 2])

tic = timeit.default_timer()
for i in range(len(data)):
    # Calculate the row's mean and standard deviation and 
    # save it directly into the pre-allocated all_stats matrix
    all_stats[i,:] = [np.mean(data[i,:]), np.std(data[i,:])]

toc = timeit.default_timer()

print("Elapsed time = %5.2f seconds"%(toc - tic))

Elapsed time =  2.88 seconds


We see that it over half the time was spent allocating and appending into the `all_stats` matrix instead of any actual data procesing.

Even better is to eliminate the for-loop entirely and compute using the vectorized `np.mean` and `np.std` functions.

In [88]:
tic = timeit.default_timer()
mean = np.mean(data, axis = 1)
std = np.std(data, axis = 1)
all_stats = np.concatenate((mean[:, np.newaxis], std[:, np.newaxis]), axis = 1)
toc = timeit.default_timer()

print("Elapsed time = %5.2f seconds"%(toc - tic))

Elapsed time =  0.08 seconds


This is much, much faster, but depends on the existence of the vectorized functions.

# Resources
---

* `numpy` Quick-start: https://docs.scipy.org/doc/numpy/user/quickstart.html

* `numpy` basics: https://docs.scipy.org/doc/numpy/user/basics.html